
export const ANNOUNCEMENT_REQUEST = "ANNOUNCEMENT_REQUEST";
export const ANNOUNCEMENT_SUCCESS = "ANNOUNCEMENT_SUCCESS";
export const ANNOUNCEMENT_FAIL = "ANNOUNCEMENT_FAIL";

export const ANNOUNCEMENT_BROWSE_REQUEST = "ANNOUNCEMENT_BROWSE_REQUEST";
export const ANNOUNCEMENT_BROWSE_SUCCESS = "ANNOUNCEMENT_BROWSE_SUCCESS";
export const ANNOUNCEMENT_BROWSE_FAIL = "ANNOUNCEMENT_BROWSE_FAIL";

export const ANNOUNCEMENT_EDIT_REQUEST = "ANNOUNCEMENT_EDIT_REQUEST";
export const ANNOUNCEMENT_EDIT_SUCCESS = "ANNOUNCEMENT_EDIT_SUCCESS";
export const ANNOUNCEMENT_EDIT_FAIL = "ANNOUNCEMENT_EDIT_FAIL";

export const ANNOUNCEMENT_DELETE_REQUEST = "ANNOUNCEMENT_DELETE_REQUEST";
export const ANNOUNCEMENT_DELETE_SUCCESS = "ANNOUNCEMENT_DELETE_SUCCESS";
export const ANNOUNCEMENT_DELETE_FAIL = "ANNOUNCEMENT_DELETE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
